---
- name: Reload systemd units
  become: true
  systemd:
    name: "{{ reload_item.dest | basename }}"
    daemon_reload: true
  with_items: "{{ reload_units.results }}"
  loop_control:
    loop_var: reload_item
  listen: "Reload systemd units"
