---
- name: Check for uninstall signal
  when: perform_uninstall
  block:
    - name: Broadcast uninstall signal
      command: /bin/true
      notify: Uninstall config
  always:
    - name: Flush handlers
      meta: flush_handlers
    - name: End play following uninstallation
      meta: end_play
  tags:
    - preflight
